import Navbar from "@/components/navbar";
import "../styles/globals.css";
import Footer from "@/components/footer";
// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation"; // Optional 
import "swiper/css/pagination"; // Optional 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
